--thanh vien:
--vo xuan hoang
-- le thanh liem
-- nguyen hai phuc khang
--pham van nhan
CREATE DATABASE BAIXE1
USE BAIXE1
--TAO BANG
CREATE TABLE XE(
TENCHUXE NVARCHAR(20) FOREIGN KEY(TENCHUXE) REFERENCES CHUXE,
BIENSO NVARCHAR(10) PRIMARY KEY,
LOAIXE NVARCHAR(20),
);
GO
--BANG CHU XE
CREATE TABLE CHUXE(
TENCHUXE NVARCHAR(20) PRIMARY KEY,
SOCMND INT,
BIENSOXE NVARCHAR(20),
);
GO
--BANG THE XE
CREATE TABLE THEXE(
MAVEXE INT,
BIENSO NVARCHAR(10) FOREIGN KEY (BIENSO) REFERENCES XE,
THOIGIAN DATETIME,
HINHANH NVARCHAR(20),
PRIMARY KEY(MAVEXE,HINHANH),
)

--BANG LAY XE
CREATE TABLE LAYXE(
MAVEXE INT,
BIENSOXE NVARCHAR(20),
HINHANH NVARCHAR(20) FOREIGN KEY (HINHANH) REFERENCES THEXE,
PRIMARY KEY(BIENSOXE,HINHANH,MAVEXE)

)

--THEM DU LIEU

INSERT INTO XE(N'PHU NGU',N'72-S1-6633',N'HONDA'),
INSERT INTO XE(N'LIEM', N'59-S1-6633,N'59-S1-6633'),
INSERT INTO XE(N'KHANG',N'48-S1-6633',N'SUZUKI'),

INSERT INTO CHUXE(N'PHU NGU',213864,N'72-S1-6633'),
INSERT INTO CHUXE(N'LIEM', 558715,N'59-S1-6633'),
INSERT INTO CHUXE(N'PHU NGU',213864,N'72-S1-6633'),

INSERT INTO THEXE(12 ,N'72-S1-6633','20/10/2018',NULL),
INSERT INTO THEXE(13 ,N'59-S1-6633,'20/10/2018',NULL),
INSERT INTO THEXE(14 ,N'48-S1-6633','20/10/2018',NULL),

INSERT INTO LAYXE(N'72-S1-6633',546546,NULL),
INSERT INTO LAYXE(N'59-S1-6633,546546,NULL),
INSERT INTO LAYXE(N'48-S1-6633',546546,NULL),
--TAO CAC SP
-- SP_THEM XE(CHU XE, BIEN SO XE, LOAI XE)
CREATE PROC SP_THEMXE(@CHUXE NVARCHAR(20), @BIENSO NVARCHAR(10),@LOAIXE NVARCHAR(20))
AS 
	INSERT INTO XE(TENCHUXE, BIENSO, LOAIXE)
	VALUES (@CHUXE,@BIENSO,@LOAIXE)
--THUC THI
EXEC SP_THEMXE N'PHU NGU',N'72-S1-6633',N'HONDA'

--SP_THEM CHU XE(CHU XE, CMND, BIEN SO)
CREATE PROC SP_THEMCHUXE(@CHUXE NVARCHAR(20), @CMND INT, @BIENSO NVARCHAR(20))
AS
	INSERT INTO CHUXE(TENCHUXE, SOCMND,BIENSOXE)
	VALUES (@CHUXE, @CMND, @BIENSO)
--THUC THI THEM CHU XE
EXEC SP_THEMCHUXE N'PHU NGU',213864,N'72-S1-6633'

GO
-- THEM THE XE(MA VE XE, BIEN SO, THOI GIAN, HINHANH)
CREATE PROC SP_THEMTHEXE(@MAVE INT, @BIENSO NVARCHAR(10), @THOIGIAN DATETIME, @HINHANH NVARCHAR(20),)
AS
	SET DATEFORMAT DMY
	INSERT INTO THEXE(MAVEXE,BIENSO,THOIGIAN)
	VALUES (@MAVE,@BIENSO,@THOIGIAN)

GO
 -- THUC THI
 SELECT * FROM THEXE
 EXEC SP_THEMTHEXE 12 ,N'72-S1-6633','20/10/2018'
 --SP_ LAY XE(BIEN SO, ID, HINHANH)
CREATE PROC SP_LAYXE(@BIENSOXE NVARCHAR(20),@ID INT, @HINHANH NVARCHAR(20))
AS
	INSERT INTO LAYXE(BIENSOXE,ID)
	VALUES (@BIENSOXE, @ID)
-- THU THI LAY XE
EXEC SP_LAYXE N'72-S1-6633',546546